# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/fiddler-everywhere"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock]
exclude_navigation: ["knowledge-base/*"]
## List your directory names and order here, like this:
navigation:
    get-started:
        title: Get Started
        position: 10
    installation-and-setup:
        title: Installation & Setup
        position: 20
    capture-traffic:
        title: Capture Traffic
        position: 30
    inspect-traffic:
        title: Inspect Traffic
        position: 40
    modify-and-filter-traffic:
        title: Modify & Filter Traffic
        position: 50
    api:
        title: API Composing
        position: 60
    user-guide:
        title: User Interface
        position: 70
    user-guide/settings:
        title: Settings
        position: 20
    knowledge-base:
        title: Knowledge Base
        position: 100

## Product title
product: "Progress Telerik Fiddler Everywhere"
platform: fiddler-everywhere

## An experimental property to resolve the SEO vs STA panels conflicts discussed in the following issue: https://github.com/telerik/docs-seed/issues/159
## Use only with docs-seed branch #fiddler-page-title
page_title_product: "Fiddler Everywhere"
use_product_in_title: true

## The application virtual path
baseurl: /fiddler-everywhere

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "fiddler"
        editable: true

has_kb_portal: true
has_api_reference: false

# Feedback Form Google Sheet ID
ff-sheet-id: 84c25215-7f22-0eb3-160f-78751ef7a337

# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:dyayucp6jmq'
gcs_api_key: 'AIzaSyCR292MCaU5T4cBKtvla6ZJTpPjQuM6dtU'

hide_contact_support: true
edit_repo_url: https://github.com/telerik/fiddler-everywhere-docs/edit/master
download: https://www.telerik.com/download/fiddler-everywhere
nav:
  "What's New": https://www.telerik.com/support/whats-new/fiddler-everywhere
  "Release History": https://www.telerik.com/support/whats-new/fiddler-everywhere/release-history
  "About": https://www.telerik.com/fiddler-everywhere

footer:
-
  title: "Getting Started"
  links:
    "First Steps on Windows": https://docs.telerik.com/fiddler-everywhere/get-started/quickstart-windows
    "First Steps on macOS": https://docs.telerik.com/fiddler-everywhere/get-started/quickstart-macos
    "First Steps on Linux": https://docs.telerik.com/fiddler-everywhere/get-started/quickstart-linux
    "Download Now": https://www.telerik.com/download/fiddler-everywhere
    "License": https://www.telerik.com/purchase/license-agreement/fiddler-everywhere
-
  title: "Support Resources"
  links:
    "All Things Fiddler": https://www.telerik.com/blogs/fiddler
    "Fiddler Videos": https://www.telerik.com/videos/fiddler/tag/fiddler-everywhere
    "Fiddler Webinars": https://www.telerik.com/webinars/fiddler-everywhere
    "What's New": https://www.telerik.com/support/whats-new/fiddler-everywhere
    "Roadmap": https://www.telerik.com/support/whats-new/fiddler-everywhere/roadmap
    "Release History": https://www.telerik.com/support/whats-new/fiddler-everywhere/release-history
-
  title: "Community"
  links:
    "Feedback Portal": https://feedback.telerik.com/fiddler-everywhere
    "Fiddler Forums": https://community.getfiddler.com/support/discussions
    "Fiddler Blogs": https://www.telerik.com/blogs/tag/fiddler
    "FAQ": https://www.telerik.com/fiddler/fiddler-everywhere/faq



footer_social:
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/
    twitter: https://twitter.com/TelerikFiddler/

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
